<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;

/*
 * Implement hook_theme.
 */
function pulso_battool_theme($existing, $type, $theme, $path): array {
  return [
    'mental_resilience_teaser_block' => [
      'variables' => [
        'data' => NULL,
      ],
    ],
    'mental_resilience_teaser_2_block' => [
      'variables' => [
        'data' => NULL,
      ],
    ],
    'mental_resilience_block' => [
      'variables' => [
        'data' => NULL,
        'mentalResilienceForm' => NULL,
      ],
    ],
    'mental_resilience_form' => [
      'render element' => 'form',
    ],
    'mental_resilience_work_situation_form' => [
      'render element' => 'form',
    ],
    'mental_resilience_results' => [
      'render element' => 'form',
    ],
    'fieldset__mental_resilience_form' => [
      'render element' => 'children',
    ],
    'form_element__mental_resilience_form' => [
      'render element' => 'children',
    ],
  ];
}

/*
 * Implements template_preprocess_form().
 */
function pulso_battool_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case "mental_resilience_stress_form" :
      pulso_battool_attach_form_id($form, $form_id);
      break;
  }
}

/**
 * Attaches form id to all form elements.
 *
 * @param $form
 *   The form or form element which children should have form id attached.
 * @param $form_id
 *   The form id attached to form elements.
 *
 * @return array
 */
function pulso_battool_attach_form_id(&$form, $form_id) {
  foreach (Element::children($form) as $child) {
    if (!isset($form[$child]['#form_id'])) {
      $form[$child]['#form_id'] = $form_id;
    }
    pulso_battool_attach_form_id($form[$child], $form_id); // recurse for children
  }
}

/*
 * Implements hook_theme_suggestions_HOOK_alter()
 */
function pulso_battool_theme_suggestions_fieldset_alter(array &$suggestions, array $variables) {
  if (isset($variables["element"]["#form_id"]) && $variables["element"]["#form_id"] === "mental_resilience_stress_form" && in_array("questions", $variables["element"]["#array_parents"])) {
    $suggestions[] = 'fieldset__mental_resilience_form';
  }
}

/**
 * Implementation of hook_theme_suggestions_form_element_alter().
 */
function pulso_battool_theme_suggestions_form_element_alter(array &$suggestions, array $variables) {
  if (isset($variables["element"]["#array_parents"]) && in_array("questions", $variables["element"]["#array_parents"])) {
    // This causes conflicts with Drupal / Varbase
    // $suggestions[] = 'form_element__mental_resilience_form';
  }
}
