<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;

/*
 * Implement hook_theme.
 */
function pulso_battool_theme($existing, $type, $theme, $path): array {
  return [
    'mental_resilience_teaser_block' => [
      'variables' => [
        'data' => NULL,
      ],
    ],
    'mental_resilience_teaser_2_block' => [
      'variables' => [
        'data' => NULL,
      ],
    ],
    'mental_resilience_block' => [
      'variables' => [
        'data' => NULL,
        'mentalResilienceForm' => NULL,
      ],
    ],
    'mental_resilience_form' => [
      'render element' => 'form',
    ],
    'mental_resilience_work_situation_form' => [
      'render element' => 'form',
    ],
    'mental_resilience_results' => [
      'render element' => 'form',
    ],
    'fieldset__mental_resilience_form' => [
      'render element' => 'children',
    ],
    'form_element__mental_resilience_form' => [
      'render element' => 'children',
    ],
  ];
}

/*
 * Implements template_preprocess_form().
 */
function pulso_battool_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case "mental_resilience_stress_form" :

      break;
  }
}

/*
 * Implements hook_theme_suggestions_HOOK_alter()
 */
function pulso_battool_theme_suggestions_fieldset_alter(array &$suggestions, array $variables) {
  if (isset($variables["element"]["#array_parents"]) && in_array("questions", $variables["element"]["#array_parents"])) {
    $suggestions[] = 'fieldset__mental_resilience_form';
  }
}

/**
 * Implementation of hook_theme_suggestions_form_element_alter().
 */
function pulso_battool_theme_suggestions_form_element_alter(array &$suggestions, array $variables) {
  if (isset($variables["element"]["#array_parents"]) && in_array("questions", $variables["element"]["#array_parents"])) {
    $suggestions[] = 'form_element__mental_resilience_form';
  }
}
